<a href="https://colab.research.google.com/github/samurai5634/COdes/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('dataset.csv')

In [6]:
data.head()


id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [7]:
data ['tags'] = data['genre'] + data['overview']

In [8]:
data.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count', 'tags'],
      dtype='object')

In [9]:
data.info

<bound method DataFrame.info of           id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre original_language  \
0                                          Drama,Crime                en   
1                                 Comedy,Drama,Romance     

In [10]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
 9   tags               9985 non-null   object 
dtypes: float64(2), int64(2), object(6)
memory usage: 781.4+ KB


In [11]:
data['tags']

0       Drama,CrimeFramed in the 1940s for the double ...
1       Comedy,Drama,RomanceRaj is a rich, carefree, h...
2       Drama,CrimeSpanning the years 1945 to 1955, a ...
3       Drama,History,WarThe true story of how busines...
4       Drama,CrimeIn the continuing saga of the Corle...
                              ...                        
9995    Action,Adventure,FantasyThe story follows the ...
9996    Action,TV Movie,Science Fiction,Comedy,Adventu...
9997    Action,Science Fiction,WarDuring World War II,...
9998    Adventure,Fantasy,Action,DramaA man named Farm...
9999    Thriller,Action,CrimeSeeking justice for his p...
Name: tags, Length: 10000, dtype: object

In [12]:
data_1 = data[['id','tags','title']]

In [13]:
data_1.head()

id                                               tags  \
0    278  Drama,CrimeFramed in the 1940s for the double ...   
1  19404  Comedy,Drama,RomanceRaj is a rich, carefree, h...   
2    238  Drama,CrimeSpanning the years 1945 to 1955, a ...   
3    424  Drama,History,WarThe true story of how busines...   
4    240  Drama,CrimeIn the continuing saga of the Corle...   

                         title  
0     The Shawshank Redemption  
1  Dilwale Dulhania Le Jayenge  
2                The Godfather  
3             Schindler's List  
4       The Godfather: Part II

In [31]:
data_1.shape

(10000, 3)

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer(max_features=10000,stop_words='english')

In [32]:
data_1['tags'] = data_1['tags'].fillna('')

C:\Users\Admin\AppData\Local\Temp\ipykernel_28996\3825542859.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['tags'] = data_1['tags'].fillna('')


In [33]:
cv.fit_transform(data_1['tags'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 230553 stored elements and shape (10000, 10000)>

In [34]:
vec = cv.fit_transform(data_1['tags']).toarray()

In [ ]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
vec.shape

(10000, 10000)

In [38]:
data.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count                                               tags  
0           8.7       21862  Drama,CrimeFramed in the 1940s for the double ...  
1           8.7        3731  Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2           8.7       16280  Drama,CrimeSpanning the years 1945 to 1955, a ...  
3           8.6       12959  Drama,History,WarThe true story of how busines...  
4           8.6        9811  Drama,CrimeIn the continuing saga of the Corle...

In [19]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
sin = cosine_similarity(vec)

In [21]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
sin[89]

array([0.05025189, 0.        , 0.        , ..., 0.        , 0.06299408,
       0.        ])

In [47]:
data_1 [data_1['title'] == "Schindler's List"]

id                                               tags             title
3  424  Drama,History,WarThe true story of how busines...  Schindler's List

In [52]:
dis = sorted(list(enumerate(sin[25])), reverse = True,key = lambda x:x[1])

In [53]:
dis

[(25, np.float64(1.0000000000000002)),
 (2031, np.float64(0.33796318470968734)),
 (4520, np.float64(0.2785242495291166)),
 (3351, np.float64(0.26590801173915524)),
 (996, np.float64(0.25756371316446414)),
 (3, np.float64(0.2461829819586655)),
 (3571, np.float64(0.23897605969962166)),
 (229, np.float64(0.23883257361061283)),
 (2130, np.float64(0.23354968324845687)),
 (876, np.float64(0.23262105259961777)),
 (1842, np.float64(0.2321035412742638)),
 (5104, np.float64(0.2321035412742638)),
 (5826, np.float64(0.2321035412742638)),
 (6753, np.float64(0.22792115291927595)),
 (208, np.float64(0.2262778643423326)),
 (8326, np.float64(0.2175970699446223)),
 (2435, np.float64(0.21212121212121215)),
 (2873, np.float64(0.20994555243259122)),
 (1171, np.float64(0.2059714602177749)),
 (59, np.float64(0.20100756305184245)),
 (5556, np.float64(0.20100756305184245)),
 (5757, np.float64(0.20100756305184242)),
 (1889, np.float64(0.20032733246124987)),
 (4843, np.float64(0.19968076595771794)),
 (3844, np.f

In [51]:
for i in dis[0:5]:
  print (data_1.iloc[i[0]].title)

Mommy
Things We Lost in the Fire
3 Generations
The Pursuit of Happyness
Closet Monster


In [27]:
def recommend(movies):
  index = data_1[data_1['title'] == movies].index[0]
  dist = sorted(list(enumerate(sin[index])), reverse = True,key = lambda vec:vec[1])
  for i  in dist[0:5]:
    print (data_1.iloc[i[0]].title)

In [54]:
recommend('The Pursuit of Happyness')

The Pursuit of Happyness
The Hunt
Promised Land
Black or White
Like Father, Like Son
